//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string Name { get; set; }
        public string PIB { get; set; }
        public string Address { get; set; }
        public string AccountNo { get; set; }
        public Nullable<bool> Deposit { get; set; }
    }
}
