//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string employeeId { get; set; }
        public string employeeFirstName { get; set; }
        public string employeeLastName { get; set; }
        public string employeeEmail { get; set; }
        public string employeePassword { get; set; }
        public string employeeStatus { get; set; }
        public double employeeSalary { get; set; }
        public Nullable<System.DateTime> employeeBirthDate { get; set; }
        public string employeeType { get; set; }
    }
}
