//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        public string Id { get; set; }
        public string RecepitId { get; set; }
        public string RampId { get; set; }
        public string VehicleId { get; set; }
        public string StorekeeperId { get; set; }
        public bool Loaded { get; set; }
        public string ReportId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Ramp Ramp { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual Report Report { get; set; }
    }
}
